export {Author} from './author.js'
export {BookCollection} from './book-collection.js'
export {Book} from './book.js'
export {Collection} from './collection.js'
export {Notepad} from './notepad.js'
export {Product} from './product.js'
export {Ratingable} from './ratingable.js'
